CanalTP\NavitiaIoCoreApiBundle\Entity\User:
    exclusion_policy: ALL
    access_type: property
    xml_root_name: user
    properties:
        firstName:
            expose: true
        lastName:
            expose: true
        projectType:
            expose: true
        tokens:
            expose: true
        company:
            expose: true
        createdAt:
            expose: true
